site_name: Ultimate Kubernetes Bootcamp
pages:
  - Home: "index.md"
  - Setup:
     - Using minikube to setup single node environment: "minikube.md"
     - Provisioning VMs with Vagrant: "2_kube_cluster_vagrant.md"
     - Setup Kubernetes Cluster: "3_install_kubernetes.md"
     - Kuberentes Visualizer : "kube_visualizer.md"
     - Kubernetes Quickdive: "quickdive.md"
  - Kubernetes Fundamentals:
     - Launching Pods: "5-vote-deploying_pods.md"
     - Making application highly available: "replication.md"
     - Publishing appliaction and Service Discovery: "7-vote-exposing_app_with_service.md"
     - Defining Update Strategy: "6-vote-kubernetes_deployment.md"
     - Mini Project: "11_deploying_sample_app.md"
     - Managing Configurations and Secrets: "9-vote-configmaps_and_secrets.md"
     - Making Data Persist: "vote-persistent-volumes.md"
  - Advanced Kubernetes:
     - Kubespray HA lab setup with Vagrant: "kubespray-prereqs.md"
     - HA setup with Kubespray: "cluster_setup_kubespray.md"
     - Authentication and Authorization (RBAC): "configuring_authentication_and_authorization.md"
     - Advanced Pod Scheduling: "advanced_pod_scheduling.md"
     - Pod Resource and Security Specs: "pod-adv-specs.md"
     - Adding health checks with Probes: "pods-health-probes.md"
     - Application Routing with Ingress Controllers : "ingress.md"
     - Auto Scaling Capacity with HPA : "10_kubernetes_autoscaling.md"
     - Creating Replicated Redis Cluster with Statefulsets: "13_redis_statefulset.md"
     - Access Control with Network Policies: "network_policies.md"
     - Cluster Administration: "cluster-administration.md"
     - Helm Charts: "helm.md"
  - Additional Topics:
     - Building Deployment Strategies: "vote-deployement_strategies.md"
     - Troubleshooting Tips: "12_troubleshooting.md"
     - Logging: "logging.md"
  - References:
     - RBAC apiGroups to Resource Mapping: "rbac-resource-group-mapping.md"
docs_dir: chapters
theme: readthedocs
plugins:
    - search
